# Imitate scripted policy
#
# python3 imitate_episodes.py \
# --task_name sim_transfer_cube_scripted \
# --ckpt_dir <ckpt dir> \
# --policy_class ACT --kl_weight 10 --chunk_size 100 --hidden_dim 512 --batch_size 8 --dim_feedforward 3200 \
# --num_epochs 2000  --lr 1e-5 \
# --seed 0

task_config_dir: config
task_name:
  - sim_insertion_scripted
  - sim_transfer_cube_scripted
ckpt_dir: ckpt
policy_class: ACT
kl_weight: 10
chunk_size: 80
hidden_dim: 512
batch_size: 8
dim_feedforward: 3200
num_epochs: 10000
lr: 1.e-5
seed: 0

# Additional arguments that are needed
eval: False
onscreen_render: False
temporal_agg: False
eval_task: None