# Parameters from the record_sim_episodes.py script
#
# python3 record_sim_episodes.py \
#    --task_name sim_insertion_scripted \
#    --dataset_dir <data save dir> \
#    --num_episodes 50
#
task_name: sim_insertion_scripted
dataset_dir: data/sim_insertion_scripted
num_episodes: 50
onscreen_render: False

# Data from constants.py
#
# 'sim_insertion_scripted': {
#     'dataset_dir': DATA_DIR + '/sim_insertion_scripted',
#     'num_episodes': 50,
#     'episode_len': 400,
#     'camera_names': ['top']
# },
episode_len: 400
camera_names: ['top', 'angle', 'vis']
